6g0dax
PowerQuery (M) Text.Contains function with OR logical operator.
Hi, I have a column with site domains like:

* juegos.abc.com
* blogs.abc.com
* reddit.com
* elpais.com

I want to crate a conditional column, that tells me if a domain is "media" or "community" based on a given list of domains.

I can do it manually from "create conditional column" in PowerBi but it will take me a million years.

Instead I've tried:

#"Added Conditional Column18" = Table.AddColumn(#"Added Conditional Column17", "sitio.tipo", each if Text.Contains([Content.thread.site], "elpais OR elmundo OR elconfidencial OR abc OR lavanguardia OR 20minutos OR eldiario OR rtve OR elespanol OR eleconomista OR publico OR telecinco OR lasexta OR cuatro") then "medio" else "comunidad" )

Not working.

Also tried:

#"Added Conditional Column18" = Table.AddColumn(#"Added Conditional Column17", "sitio.tipo", each if Text.Contains([Content.thread.site], "elpais" OR "elmundo" OR "elconfidencial" OR "abc" OR "lavanguardia" OR "20minutos" OR "eldiario" OR "rtve" OR "elespanol" OR "eleconomista" OR "publico" OR "telecinco" OR "lasexta" OR "cuatro") then "medio" else "comunidad" )


Same problem. I tried to find how to use operators withing the documentation, but it doesn't say much. Just what operators you can use, but I don't really know how to use it within this formula.


-------------
Yeah, that's not how OR works 

- You'd need an OR between each boolean expression:

        If TextContains([content.thread.site], "elpais") 
           OR Text.Contains([content.thread.site], "elmundo") 
           OR etc
 
It's certainly *not* the best way to do it anyway.

- "Lookups" in PQ usually involve merging tables - looking for a partial match in this case. Example: https://superuser.com/questions/1115130/excel-power-query-or-anything-else-join-on-partial-match-between-fields
- may also be sensible to write an M function which determines whether for each item in a list, for example, whether the site name is LIKE a name on a list: https://blog.crossjoin.co.uk/2014/05/27/implementing-a-basic-likewildcard-search-function-in-power-query/

This [example is quite similar to what you are trying to achieve](https://blog.crossjoin.co.uk/2015/01/08/multiselect-filtering-and-functions-in-power-query/). Instead of Yes/No you'd have "medio" and if it didn't match "comunidad".
-------------
Solution Verified
-------------

You have awarded one point to _small_trunks_.    
[^Find ^out ^more ^here.](https://www.reddit.com/r/excel/wiki/clippy)

